### ISSUE TITLE
Add an ErrorReadableStream

### ISSUE THREAD

**Issue by wdullaer** [jogabo/stream-util#1]
I was creating a similar library for work.
The only thing I had which is not in here is an ErrorReadableStream, which emits and error when trying to call _read. This is useful in mocks when testing.

Would you be open to a PR for this?

**Comment by pgherveou** [comment]
Hi I am not sure to understand? could you show me a small snippet of how you would use that?

**Comment by wdullaer** [comment]
I use it in my tests when I want to test error handling.
I'll mock a function which generates a ReadableStream and make it return the ErrrorReadableStream.
I can then test the error handling of the pipes in place.

**Comment by pgherveou** [comment]
Why dont you just emit an en error from your stream?

**Comment by wdullaer** [comment]
Consider the following case with a mongodb query:

```javascript
collection.find()
    .on('error', (error) => {
        console.error(error);
        res.status(500).send();
    })
    .pipe(someTransform)
    .pipe(res);
```
find() creates a cursor which is a ReadableStream. Find is code from another library, it's not my code, but I'd still like to test this pipeline, including the error handling.

In my test I'll mock out the `find` function. In one test I'll use `streamUtil.fromArray()`, to pass in some dummy data. In another test I'll mock it with a stream that emits an error on read. That's the bit I'd like to add to this library, it is a nice utility when testing code.

**Comment by pgherveou** [comment]
how about 
```js
streamUtil.fromArray([new Error()])
```
to generate your error? that would work?

**Comment by wdullaer** [comment]
This would push an error object onto the stream rather than emit an error event I think.

**Comment by pgherveou** [comment]
you are right. my bad. This would work though and its quite easy to write, I am not sure adding another signature to the api would make sense. Let me know what you think 
```js
import { readAsync } from 'stream-util'
readAsync(() => Promise.reject(new Error()))  
```

**Comment by wdullaer** [comment]
I hadn't considered that. It's a nice oneliner that can replace my custom Readable.

Thanks for the input :-)

**Comment by pgherveou** [comment]
Cool
By the way if you had written some tests on the lib u created, We could use it for stream-util

**Comment by wdullaer** [comment]
I didn't. It was an intermediate fix for a problem.
But writing some tests for this library shouldn't be too hard. I'll see if I can spend some time on it in the next few weeks.
